In [1]:
import pandas as pd
import numpy as np

# %load_ext autoreload
# %autoreload 2

In [ ]:
Input variables (based on physicochemical tests):
   1 - fixed acidity
   2 - volatile acidity
   3 - citric acid
   4 - residual sugar
   5 - chlorides
   6 - free sulfur dioxide
   7 - total sulfur dioxide
   8 - density
   9 - pH
   10 - sulphates
   11 - alcohol
   Output variable (based on sensory data): 
   12 - quality (score between 0 and 10)

In [7]:
col_names = ['fixed_acidity',
             'volatile_acidity',
             'citric_acid',
             'residual_sugar',
             'chlorides',
             'free_sulfur',
             'total_sulfur',
             'density',
             'pH',
             'sulphates',
             'alcohol',
            ]

In [87]:
Xy = np.loadtxt("winequality-white.csv", delimiter=";", skiprows=1)

X = Xy[:, 0:-1]
y = Xy[:, -1]

In [71]:
df_x = pd.DataFrame(X, columns=col_names)
print(df_x.head())

df_y = pd.DataFrame(y, columns=['quality'])
print(df_y.head())

   fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free_sulfur  total_sulfur  density    pH  sulphates  alcohol  
0         45.0         170.0   1.0010  3.00       0.45      8.8  
1         14.0         132.0   0.9940  3.30       0.49      9.5  
2         30.0          97.0   0.9951  3.26       0.44     10.1  
3         47.0         186.0   0.9956  3.19       0.40      9.9  
4         47.0         186.0   0.9956  3.19       0.40      9.9  
   quality
0      6.0
1      6.0
2      6.0
3      6.0
4      6.0


In [3]:
def RidgeRegression(x, y, lmbda=0.1):
    XtX_inv = np.linalg.inv(x.T.dot(x) + lmbda*np.eye(x.shape[1]))
    XtY = np.dot(x.T,y)
    
    return np.dot(XtX_inv,XtY)

In [15]:
print(RidgeRegression(X, y, 0.1))
print(RidgeRegression(df_x, df_y, 0.1))

[-4.93525219e-02 -1.95424936e+00 -2.93449944e-02  2.51093561e-02
 -8.83134271e-01  4.80475380e-03 -8.81650731e-04  1.99109659e+00
  1.77882027e-01  4.15953639e-01  3.66346412e-01]
[[-4.93525219e-02]
 [-1.95424936e+00]
 [-2.93449944e-02]
 [ 2.51093561e-02]
 [-8.83134271e-01]
 [ 4.80475380e-03]
 [-8.81650731e-04]
 [ 1.99109659e+00]
 [ 1.77882027e-01]
 [ 4.15953639e-01]
 [ 3.66346412e-01]]


In [6]:
from myalgorithm.ridge_regression import ridge_regression
ridge_regression(X, y, 0.1)

array([-4.93525219e-02, -1.95424936e+00, -2.93449944e-02,  2.51093561e-02,
       -8.83134271e-01,  4.80475380e-03, -8.81650731e-04,  1.99109659e+00,
        1.77882027e-01,  4.15953639e-01,  3.66346412e-01])

In [ ]:
from myalgorithm.ridge_regression import RidgeRegression
rr = RidgeRegression(penalty=0.2)
rr.fit(X=df_x, y=df_y)

rr_sgd = RidgeRegression(penalty=0.2, opt='sgd', lr=0.001)
rr_sgd.fit(X=X, y=y)
# rr_np = RidgeRegression(penalty=0.2)
# rr_np.fit(X,y)

C:\Users\alai\Documents\Python Projects\ChiPy_Spring2018\ModelExamples\RidgeRegression\myalgorithm\ridge_regression.py:53: RuntimeWarning: invalid value encountered in add
  self.beta = pt1 + pt2


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
> c:\users\alai\documents\python projects\chipy_spring2018\modelexamples\ridgeregression\myalgorithm\ridge_regression.py(40)fit()
-> for i, xi in enumerate(X):
(Pdb) pt1
array([-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf])
(Pdb) p1
[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([8.39664000e-02, 

(Pdb) p2
[array([8.4000e-02, 3.2400e-03, 4.3200e-03, 2.4840e-01, 5.4000e-04,
       5.4000e-01, 2.0400e+00, 1.2012e-02, 3.6000e-02, 5.4000e-03,
       1.0560e-01]), array([-3.43861173e+00, -1.63743416e-01, -1.85575871e-01, -8.73298218e-01,
       -2.67447579e-02, -7.64135941e+00, -7.20471030e+01, -5.42536518e-01,
       -1.80117758e+00, -2.67447579e-01, -5.18520817e+00]), array([1.15005768e+02, 3.97550804e+00, 5.67929720e+00, 9.79678767e+01,
       7.09912150e-01, 4.25947290e+02, 1.37722957e+03, 1.41286716e+01,
       4.62862722e+01, 6.24722692e+00, 1.43402254e+02]), array([-3.83025139e+03, -1.22355253e+02, -1.70233395e+02, -4.52182456e+03,
       -3.08548028e+01, -2.50030299e+04, -9.89481609e+04, -5.29638650e+02,
       -1.69701416e+03, -2.12791744e+02, -5.26659566e+03]), array([2.79905472e+05, 8.94142478e+03, 1.24402432e+04, 3.30443959e+05,
       2.25479408e+03, 1.82716072e+06, 7.23089135e+06, 3.87047066e+04,
       1.24013674e+05, 1.55503040e+04, 3.84870023e+05]), array([-1.2227433

(Pdb) p1[1]
array([8.39664000e-02, 3.23870400e-03, 4.31827200e-03, 2.48300640e-01,
       5.39784000e-04, 5.39784000e-01, 2.03918400e+00, 1.20071952e-02,
       3.59856000e-02, 5.39784000e-03, 1.05557760e-01])
(Pdb) p2[1]
array([-3.43861173e+00, -1.63743416e-01, -1.85575871e-01, -8.73298218e-01,
       -2.67447579e-02, -7.64135941e+00, -7.20471030e+01, -5.42536518e-01,
       -1.80117758e+00, -2.67447579e-01, -5.18520817e+00])


In [106]:
rr_sgd.beta

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [96]:
y[:10]

array([6., 6., 6., 6., 6., 6., 6., 6., 6., 6.])

In [97]:
rr.beta

array([-4.81835161e-02, -1.94992120e+00, -2.92417298e-02,  2.52215689e-02,
       -8.29971859e-01,  4.81834518e-03, -8.85493794e-04,  1.94321236e+00,
        1.86849322e-01,  4.15461148e-01,  3.66998785e-01])

In [100]:
[0,2,2412,2].shape

AttributeError: 'list' object has no attribute 'shape'